### ISSUE TITLE
Pinapple.py Error

### ISSUE THREAD

**Issue by yu3ufe** [clutch70/freqtrade_public#1]
When I'm backtesting Pineapple strat, I keep getting this error

`2022-08-09 16:56:30,687 - freqtrade - ERROR - Fatal exception!
Traceback (most recent call last):
  File "/home/joo/freqtrade/freqtrade/main.py", line 37, in main
    return_code = args['func'](args)
  File "/home/joo/freqtrade/freqtrade/commands/optimize_commands.py", line 57, in start_backtesting
    backtesting = Backtesting(config)
  File "/home/joo/freqtrade/freqtrade/optimize/backtesting.py", line 99, in __init__
    self.strategylist.append(StrategyResolver.load_strategy(self.config))
  File "/home/joo/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 88, in load_strategy
    StrategyResolver._normalize_attributes(strategy)
  File "/home/joo/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 130, in _normalize_attributes
    strategy.stoploss = float(strategy.stoploss)
TypeError: float() argument must be a string or a number, not 'DecimalParameter'`

I tried manipulating hyperopt parameters but no success!

**Comment by clutch70** [comment]
Oh my brother in dev - its very much a WIP! I don't think I've even loaded it in to a testing instance of freqtrade yet! Its insanely stupid right now, it just considers the RSI to enter and exit.

The idea is to make a longer timeframe strat that will swing (swing.. like swingers... ergo Pineapple) trade dailies and 4 hours etc... if that interests you I'll definitely keep you posted as I keep building it!

From: xaveedra ***@***.***>
Sent: Tuesday, August 9, 2022 8:59 AM
To: clutch70/freqtrade_public ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [clutch70/freqtrade_public] Pinapple.py Error (Issue #1)


When I'm backtesting Pineapple strat, I keep getting this error

2022-08-09 16:56:30,687 - freqtrade - ERROR - Fatal exception! Traceback (most recent call last): File "/home/joo/freqtrade/freqtrade/main.py", line 37, in main return_code = args['func'](args) File "/home/joo/freqtrade/freqtrade/commands/optimize_commands.py", line 57, in start_backtesting backtesting = Backtesting(config) File "/home/joo/freqtrade/freqtrade/optimize/backtesting.py", line 99, in __init__ self.strategylist.append(StrategyResolver.load_strategy(self.config)) File "/home/joo/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 88, in load_strategy StrategyResolver._normalize_attributes(strategy) File "/home/joo/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 130, in _normalize_attributes strategy.stoploss = float(strategy.stoploss) TypeError: float() argument must be a string or a number, not 'DecimalParameter'

I tried manipulating hyperopt parameters but no success!

-

**Comment by yu3ufe** [comment]
got it, thanks for your efforts. Keep going
